#BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM #BY MR VIRUS SPM 

bl='\033[34;1m'
gr='\033[32;1m'
pur='\033[35;1m'
cy='\033[36;1m'
red='\033[31;1m'
wh='\033[37;1m'
yel='\033[33;1m'

clear                                                                                                                                                                            echo $bl
sleep 1
echo "__        _______ ____        _   _    _    ____ _  __ "
echo "\ \      / / ____| __ )      | | | |  / \  / ___| |/ / "
echo " \ \ /\ / /|  _| |  _ \ _____| |_| | / _ \| |   | ' /  "
echo "  \ V  V / | |___| |_) |_____|  _  |/ ___ \ |___| . \  "
echo "   \_/\_/  |_____|____/      |_| |_/_/   \_\____|_|\_\ "
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"
echo
echo
echo $red"(+) " $yel"AUTHOR"  $red" : "$yel"MR VIRUS SPM     " $red(+)"
echo $red"(+) " $yel"CNL YT"  $red" : "$yel"MR VIRUS SPM NEW " $red(+)"
echo $red"(+) " $yel"IG    "  $red" : "$yel"mvs.x_x          " $red(+)"
echo "----------------------------------------------------------"
sleep 2
echo $gr
echo "(01). 10 macam script termux hack fb"
echo "(02). kumpulan banyak script termux"
echo "(03). situs belajar hacking"
echo "(04). cara membuat link phising"
echo "(05). cara deface webbsekolah"
echo "(06). tools termux ddos"
echo "(07). hack fb dgn faceboom"
echo "(08). hack cctv terdekat"
echo "(09). hack following ig"
echo "(10). hack pulsa gratis"
echo "(11). hack whatsapp"
echo "(12). hack akun free fire"
echo "(13). chite diamond ff"
echo "(14). malacak hp yg hilang"
echo "(15). keluar....."
echo $wh
read -p "MASUKAN PILIHAN =} " hre

if [ $hre = 01 ]
then
   xdg-open https://www.ac10hacks.com/script-hack-fb-termux/
fi
if [ $hre = 02 ]
then
   xdg-open https://www.google.com/amp/s/www.thecuy.com/2021/01/16/kumpulan-script-termux-lengkap-terbaru-2021-dan-cara-menggunakan/
fi
if [ $hre = 03 ]
then
   xdg-open https://hackaday.com/
fi
if [ $hre = 04 ]
then
   xdg-open https://www.google.com/amp/s/jalantikus.com/amp/tips/cara-membuat-link-phising/
fi
if [ $hre = 05 ]
then
   xdg-open https://omcyber.com/deface-web-sekolah/
fi
if [ $hre = 06 ]
then
   xdg-open https://omcyber.com/cara-ddos-attack-termux/
fi
if [ $hre = 07 ]
then
   xdg-open https://www.magelang1337.com/2020/07/cara-hack-fb-dengan-faceboom-termux.html?m=1
fi
if [ $hre = 08 ]
then
   xdg-open https://www.cara1001.com/2021/01/cara-hack-cctv-terdekat-dengan-termux.html?m=1
fi
if [ $hre = 09 ]
then
   xdh-open https://www.ac10hacks.com/cara-hack-followers-instagram-dengan-termux-android/
fi
if [ $hre = 10 ]
then
   xdg-open https://www.ac10hacks.com/4-cara-hack-pulsa-mendapatkan-pulsa-gratis/
if [ $hre = 11 ]
then
   xdg-open https://www.ac10hacks.com/sadap-whatsapp-dengan-aplikasi-termux/
fi
if [ $hre = 12 ]
then
   xdg-open https://www.cara1001.com/2021/02/apk-hack-akun-ff.html?m=1
fi
if [ $hre = 13 ]
then
   xdg-open https://www.cara1001.com/2021/04/aplikasi-cheat-diamond-free-fire-tak-terbatas.html?m=1
fi
if [ $hre = 14 ]
then
   xdg-open https://jalantikus.com/gadgets/cara-melacak-smartphone-android-yang-hilang/
fi
if [ $hre = 15
then
   exit -y
fi